services:
  - type: web
    name: torpedo-lvivskogo
    env: python
    plan: free
    buildCommand: |
      pip install -r requirements.txt
      python manage.py collectstatic --noinput
      python manage.py migrate
    startCommand: gunicorn --bind 0.0.0.0:$PORT myproject.wsgi:application
    envVars:
      - key: DEBUG
        value: false
      - key: SITE_URL
        value: https://torpedo-lvivskogo.onrender.com